suppressPackageStartupMessages({library(arrow); library(dplyr)})
DIR <- "analysis/audit/2026-07-23-coherence"
pm <- read_parquet(file.path(DIR,"per-member-contrasts.parquet"))
cv <- readRDS(file.path(DIR,"cluster-verdicts.rds"))
# degenere = treated_label == control_label (case-insensitive, trimmed)
pm$deg <- tolower(trimws(pm$treated_label)) == tolower(trimws(pm$control_label))
cat("=== MEMBRI degeneri (treated==control) sui 38.440 risolti ===\n")
cat("n membri degeneri:", sum(pm$deg), sprintf("(%.2f%%)\n", 100*mean(pm$deg)))
cat("\n=== CLUSTER con >=1 membro degenere / interamente degeneri ===\n")
byc <- pm |> group_by(cluster_id) |> summarise(n=n(), ndeg=sum(deg), fdeg=mean(deg), k=n_distinct(study_id), .groups="drop")
cat("cluster con >=1 membro degenere:", sum(byc$ndeg>=1), "\n")
cat("cluster con MAGGIORANZA degenere (>=0.5):", sum(byc$fdeg>=0.5), "\n")
cat("cluster INTERAMENTE degeneri (fdeg==1):", sum(byc$fdeg==1), "\n")
cat("cluster interamente degeneri con k>=3:", sum(byc$fdeg==1 & byc$k>=3), "\n")
cat("\n=== esempi di membri degeneri (label identiche) ===\n")
print(head(unique(pm$treated_label[pm$deg]), 12))
